<?xml version="1.0" encoding="utf-8"?><Database Name="MyPratice" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-CIJN2E2A\SQLEXPRESS;Initial Catalog=MyPratice;Integrated Security=True" SettingsObjectName="MyLogin.Properties.Settings" SettingsPropertyName="MyPraticeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TB_M_PRODUCT" Member="TB_M_PRODUCTs">
    <Type Name="TB_M_PRODUCT">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="itemName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="design" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="color" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="expiredDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_M_USER" Member="TB_M_USERs">
    <Type Name="TB_M_USER">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>